language: minimal

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-luatex
    - tex4ht
    - texlive-fonts-recommended
    - lmodern
    - texlive-lang-french
    - ghostscript
    - imagemagick
    - netpbm
    - tidy
    - ubuntu-dev-tools
    - debhelper
    - dput
    - fakeroot
    - python-paramiko

script:
  - make dist

after_success:
  - ${TRAVIS_BUILD_DIR}/travis-ci/package.sh

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/launchpad/dput-launchpad.sh
    script: sh "${TRAVIS_BUILD_DIR}/travis-ci/launchpad/dput-launchpad.sh"
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file:
      - html/*.zip
      - pdf/**/*.pdf
    api_key:
      secure: Xs88hAj8PxJgod3P04XqdAIPdaKMb5KmWHCU12Ecm2lbuL5Ro8FTWYrkZSDKb8+NfmEyImD9znVbM3zvlznlrDxE8jHItSVtUtHYMYxQtlvqw0D7PQK14n6pZoemFi4APwLlxijFigNdIjGBxYfHWzQ8lVn3Gnm0Gfd87vHo5cfObDrqg9Mao21ucDN/NHXLRwbPkVwL5xoyWVWz4RyhoAsPRMVaOh7DNerALIeL+rA5+7klsK4o1trusvAJnb8VaO5EBgEOSs4oTp4rFsX8vDCOPJmeLZpA9Scp6k1sxACwmZDyXQVcgk+r/I8j7ZAeOY55mMjNjPw7gfEq76PuqJPF6Gt5CZE7jeJF/egkUH7vRaGWLJmLR6DWP587y7k5GudFF3DC8iusvNjNNm+bfkPMc9CqKg1B1XjIBJxVSs2rEYt0eBcticVI4DTNiJLW3tjGet66apKmgFETnftMGs95oJCfFJlGoWRIJT7I/9bL/JO6coEQh254s1oyCUvE1UO+w/bRnxJfeEotKOchpL3rPR7/OYdm3dxX+dAPsV1WMlbnuqeW1OTammvAAyGjiBExn6lhCAMqzXsoHAoOopfUE6kQ839sp5xSpHki9LWgNURmVF5O+rWxGo7jiY9Li7SV027/rbJlDa09u327kzfEj0CjyANV/GcpND3UUUs=
    on:
      tags: true
      all_branches: true
